### ISSUE TITLE
Can't start Rails 4.2.3 app with latest opal-rspec

### ISSUE THREAD

**Issue by jaredcwhite** [opal/opal-rspec#47]
I wanted to try out Opal 0.9 beta2 in a new Rails app I recently started, so I switched to the latest GitHub version of opal, opal-rails, opal-jquery, and opal-rspec in my Gemfile, and now I'm getting this error trying to start Rails server:

```
/Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rspec-a3b7139b29b6/lib/opal/rspec/pre_rack_locator.rb:4:in `require_relative': cannot load such file -- /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rspec-a3b7139b29b6/rspec-core/lib/rspec/core/ruby_project (LoadError)
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rspec-a3b7139b29b6/lib/opal/rspec/pre_rack_locator.rb:4:in `<top (required)>'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rspec-a3b7139b29b6/lib/opal/rspec/sprockets_environment.rb:4:in `require'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rspec-a3b7139b29b6/lib/opal/rspec/sprockets_environment.rb:4:in `<top (required)>'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rspec-a3b7139b29b6/lib/opal/rspec.rb:3:in `require'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rspec-a3b7139b29b6/lib/opal/rspec.rb:3:in `<top (required)>'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rspec-a3b7139b29b6/lib/opal-rspec.rb:1:in `require'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rspec-a3b7139b29b6/lib/opal-rspec.rb:1:in `<top (required)>'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rails-9f2557531dae/lib/opal/rails.rb:4:in `require'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rails-9f2557531dae/lib/opal/rails.rb:4:in `<top (required)>'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rails-9f2557531dae/lib/opal-rails.rb:1:in `require'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/bundler/gems/opal-rails-9f2557531dae/lib/opal-rails.rb:1:in `<top (required)>'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.5/lib/bundler/runtime.rb:76:in `require'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.5/lib/bundler/runtime.rb:72:in `each'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.5/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.5/lib/bundler/runtime.rb:61:in `each'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.5/lib/bundler/runtime.rb:61:in `require'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.5/lib/bundler.rb:134:in `require'
	from /Users/jwhite/RailsApps/mariposta4/config/application.rb:16:in `<top (required)>'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/jwhite/.rvm/gems/ruby-2.2.1@rails42/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

**Comment by wied03** [comment]
Yeah, that was fixed after beta 2.

@elia - Are you releasing the new version?

**Comment by wied03** [comment]
As to the details of that, it's probably happening because of the way you have to handle opal-rspec if you use it as a git dependency (as opposed to a packaged GEM). That require is trying to use the rspec version that should be bundled with opal-rspec (separate from rspec you may be using on the MRI side of a project).

The easiest solution is to use the GEM (which @elia should be releasing any hour now).

**Comment by wied03** [comment]
Just to be sure though, I re-triggered a Travis build against opal master. It built ok on 20 November but a another check would not be bad.

**Comment by wied03** [comment]
https://travis-ci.org/opal/opal-rspec/builds/92341048 - worked OK here on latest.

**Comment by elia** [comment]
Yeah sorry, will release before going to bed, I promise 😇

**Comment by elia** [comment]
Done: https://rubygems.org/gems/opal-rspec/versions/0.5.0

**Comment by wied03** [comment]
Yay! @jaredcwhite - Can you check out 0.5.0 and make sure that works OK for you ?

**Comment by jaredcwhite** [comment]
@wied03 Yep! Using the 0.5 gem and it works like a charm. Thanks! cc @elia
