### ISSUE TITLE
Get ` cannot load such file -- rake` when run test in browser.

### ISSUE THREAD

**Issue by zw963** [opal/opal-rspec#70]
#Follow README https://github.com/opal/opal-rspec/blob/releases/0-6-stable/README.md#run-specs-in-a-browser.

```rb
require 'opal/rspec'
# or use Opal::RSpec::SprocketsEnvironment.new(spec_pattern='spec/opal/**/*_spec.{rb,opal}') to customize the pattern
sprockets_env = Opal::RSpec::SprocketsEnvironment.new
run Opal::Server.new(sprockets: sprockets_env) { |s|
  s.main = 'opal/rspec/sprockets_runner'
  sprockets_env.add_spec_paths_to_sprockets
  s.debug = false
}
```

when, run `rackup`, Got following error:

```sh
/home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/opal-rspec-0.6.1/lib/opal/rspec/post_rack_locator.rb:1:in `require': cannot load such file -- rake (LoadError)
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/opal-rspec-0.6.1/lib/opal/rspec/post_rack_locator.rb:1:in `<top (required)>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/opal-rspec-0.6.1/lib/opal/rspec/cached_environment.rb:2:in `require'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/opal-rspec-0.6.1/lib/opal/rspec/cached_environment.rb:2:in `<top (required)>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/opal-rspec-0.6.1/lib/opal/rspec/sprockets_environment.rb:3:in `require'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/opal-rspec-0.6.1/lib/opal/rspec/sprockets_environment.rb:3:in `<top (required)>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/opal-rspec-0.6.1/lib/opal/rspec.rb:4:in `require'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/opal-rspec-0.6.1/lib/opal/rspec.rb:4:in `<top (required)>'
	from /home/zw963/Project/opal/testing_js_with_opal/config.ru:1:in `require'
	from /home/zw963/Project/opal/testing_js_with_opal/config.ru:1:in `block in <main>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	from /home/zw963/Project/opal/testing_js_with_opal/config.ru:in `new'
	from /home/zw963/Project/opal/testing_js_with_opal/config.ru:in `<main>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/rack-2.0.3/lib/rack/server.rb:283:in `start'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/rack-2.0.3/lib/rack/server.rb:148:in `start'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/gems/rack-2.0.3/bin/rackup:4:in `<top (required)>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/bin/rackup:23:in `load'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/bin/rackup:23:in `<main>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/bin/ruby_executable_hooks:15:in `eval'
	from /home/zw963/.rvm/gems/ruby-2.3.4@testing_js_with_opal/bin/ruby_executable_hooks:15:in `<main>'
```

in fact, just following will get same error too:

```rb
require 'opal/rspec'
```

The same issue happen when change Rakefile to:
```rb
# Add folllowing two line, will get error
require 'bundler'
Bundler.require

require 'opal/rspec/rake_task'
Opal::RSpec::RakeTask.new(:default
```

```sh
 ╰─ $ bundle list |grep opal
  * opal (0.10.5)
  * opal-rspec (0.6.1)
```

**Comment by zw963** [comment]
Add  `rake` into Gemfile fix this.

I am wonder why seldom to see add  `rake' into Gemfie, anywhy, it worked.

**Comment by zw963** [comment]
@elia , 
This issue still happen in Opal 0.11, we have to add `rake` with `opal-rspec` together into `Gemfile`, to make `opal-rspec` to work.

Following is a simple example:

```rb
# Gemfile

source 'https://rubygems.org'

# gem 'rake'
gem 'opal'
gem 'opal-sprockets', require: false
gem 'opal-jquery', github: 'opal/opal-jquery'
gem 'opal-rspec

```

```rb
# config.ru

require 'bundler'
Bundler.require

require 'opal/sprockets/server'

run Opal::Sprockets::Server.new {|s|
  s.append_path 'app'
  s.append_path 'js'
  s.main = 'application'

  # This can be used to provide a custom index file.
  s.index_path = 'index.html.erb'
}
```

When I run `rackup` in project root, got:

```sh
/home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/lib/opal/rspec/post_rack_locator.rb:1:in `require': cannot load such file -- rake (LoadError)
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/lib/opal/rspec/post_rack_locator.rb:1:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/lib/opal/rspec/cached_environment.rb:2:in `require'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/lib/opal/rspec/cached_environment.rb:2:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/lib/opal/rspec/sprockets_environment.rb:3:in `require'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/lib/opal/rspec/sprockets_environment.rb:3:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/lib/opal/rspec.rb:4:in `require'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/lib/opal/rspec.rb:4:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/lib/opal-rspec.rb:1:in `require'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/opal-rspec-0.6.1/lib/opal-rspec.rb:1:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
        from /home/zw963/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
        from /home/zw963/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
        from /home/zw963/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
        from /home/zw963/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
        from /home/zw963/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
        from /home/zw963/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
        from /home/public/Dropbox/others/Project/opal/0.10.5/conway_gol/config.ru:2:in `block in <main>'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
        from /home/public/Dropbox/others/Project/opal/0.10.5/conway_gol/config.ru:in `new'
        from /home/public/Dropbox/others/Project/opal/0.10.5/conway_gol/config.ru:in `<main>'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/server.rb:283:in `start'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/lib/rack/server.rb:148:in `start'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/gems/rack-2.0.3/bin/rackup:4:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/bin/rackup:22:in `load'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/bin/rackup:22:in `<main>'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/bin/ruby_executable_hooks:15:in `eval'
        from /home/zw963/.rvm/gems/ruby-2.3.3@conway_gol/bin/ruby_executable_hooks:15:in `<main>'
```

Thought this issue could be resolved by add `gem 'rake'` into my Gemfile, but, this annoy me a lot
for me, i think same situation for those newbie to Opal.

Anywhy, i think this could be resolved by `opal-rspec`, right?

Following is my example project: https://github.com/zw963/conway_gal
