### ISSUE TITLE
Could not found jquery when use node as task runner.

### ISSUE THREAD

**Issue by zw963** [opal/opal-rspec#71]
Following is Rakefile in my project:

```rb
# Rakefile

require 'bundler'
Bundler.require

require 'opal/rspec/rake_task'
Opal::RSpec::RakeTask.new(:default) do |server, task|
  server.append_path 'lib'
  server.append_path 'node_modules'
  task.runner = :node
end
```

I install jquery with yarn to following path: `./node_modules/jquery/dist/jquery.js`.

Following is a example spec file

```rb
# spec/1.spec
puts '000000000000000000000000000'
p require 'jquery/dist/jquery'
puts '111111111111111111111111111'
require 'opal'
require 'opal-jquery'
```

When run `rake -t`, got following message:

```sh
** Invoke default (first_time)
** Execute default
Passing a sprockets environment to Opal::Sprockets.load_asset no more needed.
  /home/zw963/.rvm/gems/ruby-2.3.4@opal_rspec_example/gems/opal-rspec-0.6.1/lib/opal/rspec/rake_task.rb:39:in `get_load_asset_code'
  /home/zw963/.rvm/gems/ruby-2.3.4@opal_rspec_example/gems/opal-rspec-0.6.1/lib/opal/rspec/rake_task.rb:51:in `block in launch_node'
  /home/zw963/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/net/http.rb:853:in `start'
Running node /tmp/opal_rspec.js20170902-5080-c1oikj 2>&1
Object freezing is not supported by Opal
000000000000000000000000000
true
111111111111111111111111111

/tmp/opal_rspec.js20170902-5080-c1oikj:4741
      throw exception;
      ^
Can't find jQuery or Zepto. jQuery must be included before opal-jquery
    at singleton_class_alloc.TMP_1 [as $new] (/tmp/opal_rspec.js20170902-5080-c1oikj:4980:15)
    at singleton_class_alloc.$$exception [as $exception] (/tmp/opal_rspec.js20170902-5080-c1oikj:4998:31)
    at Object_alloc.$$raise (/tmp/opal_rspec.js20170902-5080-c1oikj:4726:31)
    at /tmp/opal_rspec.js20170902-5080-c1oikj:69382:93
    at Opal.modules.opal/jquery/constants (/tmp/opal_rspec.js20170902-5080-c1oikj:69382:201)
    at TopScope.Opal.load (/tmp/opal_rspec.js20170902-5080-c1oikj:1957:7)
    at Object_alloc.Opal.require [as $require] (/tmp/opal_rspec.js20170902-5080-c1oikj:1981:17)
    at Opal.modules.opal/jquery/element (/tmp/opal_rspec.js20170902-5080-c1oikj:69391:8)
    at TopScope.Opal.load (/tmp/opal_rspec.js20170902-5080-c1oikj:1957:7)
    at Object_alloc.Opal.require [as $require] (/tmp/opal_rspec.js20170902-5080-c1oikj:1981:17)
```

It comment `task.runner = :node`, run with `phantomjs`, it work now.

Thanks.

**Comment by elia** [comment]
in node you probably want to fetch jquery from NPM and require it inside backticks:

```rb
require 'opal'
`Opal.global.$ = require('jquery')`
…
```

see also https://www.npmjs.com/package/jquery

---

Otherwise it's better to just use `phantomjs`
