### ISSUE TITLE
Unable to require 'nodejs' in spec

### ISSUE THREAD

**Issue by gfowley** [opal/opal-rspec#73]
My specs load some YAML files containing test data. It seems for ```require 'yaml'``` to work I must first ```require 'nodejs'``` in my spec.

Spec file: detector_spec.rb:
```ruby
require 'nodejs'
```
Rakefile specifies the ```:node``` runner:
```ruby
require 'opal/rspec/rake_task'
Opal::RSpec::RakeTask.new do |server, task|
  task.runner = :node
  server.append_path "./lib"
end
```
Running ```rake opal:rspec``` fails with error:
```
/home/gerard/.rvm/gems/ruby-2.4.2@iqeo-pitch/gems/opal-0.10.5/lib/opal/nodes/iter.rb:118: warning: constant ::Fixnum is deprecated
Passing a sprockets environment to Opal::Sprockets.load_asset no more needed.
  /home/gerard/.rvm/gems/ruby-2.4.2@iqeo-pitch/gems/opal-rspec-0.6.1/lib/opal/rspec/rake_task.rb:39:in `get_load_asset_code'
  /home/gerard/.rvm/gems/ruby-2.4.2@iqeo-pitch/gems/opal-rspec-0.6.1/lib/opal/rspec/rake_task.rb:51:in `block in launch_node'
  /home/gerard/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http.rb:877:in `start'
Running node /tmp/opal_rspec.js20180216-6137-10greyn 2>&1
Object freezing is not supported by Opal
module.js:471
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at singleton_class_alloc.$$node_require [as $node_require] (/tmp/opal_rspec.js20180216-6137-10greyn:58391:40)
    at /tmp/opal_rspec.js20180216-6137-10greyn:58678:26
    at Opal.modules.nodejs/dir (/tmp/opal_rspec.js20180216-6137-10greyn:58722:5)
    at TopScope.Opal.load (/tmp/opal_rspec.js20180216-6137-10greyn:1957:7)
    at Object_alloc.Opal.require [as $require] (/tmp/opal_rspec.js20180216-6137-10greyn:1981:17)
    at Opal.modules.nodejs (/tmp/opal_rspec.js20180216-6137-10greyn:58838:8)
```
It seems that when running the ```Opal::RSpec::RakeTask```  ```node_require``` cannot find the file ```stdlib/nodejs/node_modules/glob/glob.js```. I have verified it exists and confirmed that running ```opal -e "require 'nodejs'"``` works without error.

Am I missing anything ?

**Comment by gfowley** [comment]
Using opal-0.10.5 ( not using opal-0.11.0 because of #72 ).

**Comment by gfowley** [comment]
I have worked around this by converting my test data to JSON.
